name: localist
description: "a Todo Application with Location."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  firebase_database: ^10.4.0
  cloud_firestore: ^4.14.0
  # google_sign_in: ^6.2.1
  # map_location_picker: ^1.2.7
  # provider: ^6.1.1 
  longdo_maps_api3_flutter: ^1.11.0 # for map
  url_launcher: ^6.2.5 # for opening url
  intl: ^0.17.0 # for date formatting
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.9

# dart run flutter_native_splash:create
flutter_native_splash:
  # image: assets/images/cover_m.png
  # color: "#ffffff"
  color: "#ffffff"
  android_12:
    image: "assets/icon/icon.png"

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # image_path: "assets/icon/icon.png"
  image_path: "assets/icon/app_icon.png"

flutter:

  uses-material-design: true
  assets:
      - assets/
      - assets/images/cover_m.png
      - assets/icon/app_icon.png
      - assets/icon/icon.png
      - assets/images/cover.jpg
      - assets/images/panda.jpg
      - assets/icon/Flutter_logo.png
      - assets/icon/Firebase_logo.png